### ISSUE TITLE
may you do me a favor. i wanna transfer matlab function to python in pyarma

### ISSUE THREAD

**Issue by luyifanlu** [terryyz/PyArmadillo#3]
matlab function
`
function output =NN_F(input)

layer_nodes_num=[200,200,150,150];
bias=0.00001;
%input=traindata(:,1);
pre_layer_nodes_num=length(input);
pre_layer_nodes_value=input';         % input
for l=1:length(layer_nodes_num)
     >  curr_layer_nodes_num=layer_nodes_num(l);

    clear curr_layer_nodes_value;
    for it=1:curr_layer_nodes_num
        curr_node_input_weight=randn(1,pre_layer_nodes_num);
        xx=sum(pre_layer_nodes_value.*curr_node_input_weight);
        curr_layer_nodes_value(it)=tanh(xx/2.5);
    end
    pre_layer_nodes_value=curr_layer_nodes_value;
    pre_layer_nodes_num=curr_layer_nodes_num;
end
output=curr_layer_nodes_value;
end
`

>

**Comment by luyifanlu** [comment]
my work ,but got error--NameError: name 'curr_layer_nodes_value' is not defined

 `

from pyarma import *
import numpy as np
def out(inp):
   

>  layer_nodes_num=[200,210,150,150]

    bias=0.00001
    pre_layer_nodes_num=inp.n_rows
    pre_layer_nodes_value=inp.t()
    for l in range(len(layer_nodes_num)):
        curr_layer_nodes_num=layer_nodes_num[l]
        print(curr_layer_nodes_num)
        #curr_layer_nodes_value = mat(10,4,fill.zeros)
        for it in range(curr_layer_nodes_num):
            curr_node_input_weight=randn(1,pre_layer_nodes_num)
            xx=sum(pre_layer_nodes_value@curr_node_input_weight)
            curr_layer_nodes_value[it]= tanh(xx/2.5)
        pre_layer_nodes_value=curr_layer_nodes_value
        pre_layer_nodes_num=curr_layer_nodes_num
        #del curr_layer_nodes_value
    return curr_layer_nodes_value
`

**Comment by terryyz** [comment]
Hi @luyifanlu, from my understanding, `curr_layer_nodes_value` will change its size per iteration. You may consider initialize `curr_layer_nodes_value` by using `curr_layer_nodes_value = mat()`. Then you may want to use `.resize()` to handle the assigned values and increased size of `curr_layer_nodes_value` per iteration.

**Comment by luyifanlu** [comment]
> Hi @luyifanlu, from my understanding, `curr_layer_nodes_value` will change its size per iteration. You may consider initialize `curr_layer_nodes_value` by using `curr_layer_nodes_value = mat()`. Then you may want to use `.resize()` to handle the assigned values and increased size of `curr_layer_nodes_value` per iteration.

Thank you . i got a question whether there are cell function in pyarma like matlab. if not, which one can instead of it

**Comment by terryyz** [comment]
> > Hi @luyifanlu, from my understanding, `curr_layer_nodes_value` will change its size per iteration. You may consider initialize `curr_layer_nodes_value` by using `curr_layer_nodes_value = mat()`. Then you may want to use `.resize()` to handle the assigned values and increased size of `curr_layer_nodes_value` per iteration.
> 
> Thank you . i got a question whether there are cell function in pyarma like matlab. if not, which one can instead of it

Hi @luyifanlu, if you mean `cell()`  function in the matlab, then we don't have it as it is not implemented by Armadillo... (We may add extra features later. But we want to focus on implementing all functions of Armadillo into the PyArmadillo at this stage.). Feel free to check the [PyArmadillo documentation](https://pyarma.sourceforge.io/docs.html) in English. I'm still trying to find some time to work on the documentation translation.

And Happy Chinese New Year! 🥳

**Comment by luyifanlu** [comment]
> > > Hi @luyifanlu, from my understanding, `curr_layer_nodes_value` will change its size per iteration. You may consider initialize `curr_layer_nodes_value` by using `curr_layer_nodes_value = mat()`. Then you may want to use `.resize()` to handle the assigned values and increased size of `curr_layer_nodes_value` per iteration.
> > 
> > 
> > Thank you . i got a question whether there are cell function in pyarma like matlab. if not, which one can instead of it
> 
> Hi @luyifanlu, if you mean `cell()` function in the matlab, then we don't have it as it is not implemented by Armadillo... (We may add extra features later. But we want to focus on implementing all functions of Armadillo into the PyArmadillo at this stage.). Feel free to check the [PyArmadillo documentation](https://pyarma.sourceforge.io/docs.html) in English. I'm still trying to find some time to work on the documentation translation.
> 
> And Happy Chinese New Year!

ow ow,  i see. How to get last row. i have tried in X[-1,:] and X[end,:],but both get error.

> And Happy Chinese New Year!

**Comment by terryyz** [comment]
> > > > Hi @luyifanlu, from my understanding, `curr_layer_nodes_value` will change its size per iteration. You may consider initialize `curr_layer_nodes_value` by using `curr_layer_nodes_value = mat()`. Then you may want to use `.resize()` to handle the assigned values and increased size of `curr_layer_nodes_value` per iteration.
> > > 
> > > 
> > > Thank you . i got a question whether there are cell function in pyarma like matlab. if not, which one can instead of it
> > 
> > 
> > Hi @luyifanlu, if you mean `cell()` function in the matlab, then we don't have it as it is not implemented by Armadillo... (We may add extra features later. But we want to focus on implementing all functions of Armadillo into the PyArmadillo at this stage.). Feel free to check the [PyArmadillo documentation](https://pyarma.sourceforge.io/docs.html) in English. I'm still trying to find some time to work on the documentation translation.
> > And Happy Chinese New Year!
> 
> ow ow, i see. How to get last row. i have tried in X[-1,:] and X[end,:],but both get error.
> 
> > And Happy Chinese New Year!

Check [this](https://pyarma.sourceforge.io/docs.html#submat) in the doc.
